// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.0.3 (commit 5836c268a7307f864b33636357b0869ecc40bc0a).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AddPropertyReducer from "./add_property_reducer";
import AppendPageDocReducer from "./append_page_doc_reducer";
import AuthorizeBlobAccessReducer from "./authorize_blob_access_reducer";
import ClearBlockAccessRuleReducer from "./clear_block_access_rule_reducer";
import ClearPageAccessRuleReducer from "./clear_page_access_rule_reducer";
import ClearPropertyValueReducer from "./clear_property_value_reducer";
import CreateApiEndpointReducer from "./create_api_endpoint_reducer";
import CreateApiEndpointKeyReducer from "./create_api_endpoint_key_reducer";
import CreateApiFieldMappingReducer from "./create_api_field_mapping_reducer";
import CreateAttachmentReducer from "./create_attachment_reducer";
import CreateBlockCommentReducer from "./create_block_comment_reducer";
import CreateComponentTreePageReducer from "./create_component_tree_page_reducer";
import CreateDatabaseRowReducer from "./create_database_row_reducer";
import CreateDatabaseSchemaReducer from "./create_database_schema_reducer";
import CreateLocalUserReducer from "./create_local_user_reducer";
import CreatePageReducer from "./create_page_reducer";
import CreateViewReducer from "./create_view_reducer";
import DeleteApiEndpointReducer from "./delete_api_endpoint_reducer";
import DeleteApiFieldMappingReducer from "./delete_api_field_mapping_reducer";
import DeleteAttachmentReducer from "./delete_attachment_reducer";
import DeleteBlockCommentReducer from "./delete_block_comment_reducer";
import DeleteComponentReducer from "./delete_component_reducer";
import DeleteDatabaseRowReducer from "./delete_database_row_reducer";
import DeletePageReducer from "./delete_page_reducer";
import DeletePageSubtreeReducer from "./delete_page_subtree_reducer";
import DeletePropertyReducer from "./delete_property_reducer";
import DeleteViewReducer from "./delete_view_reducer";
import EmptyTrashReducer from "./empty_trash_reducer";
import HardenLocalPasswordsReducer from "./harden_local_passwords_reducer";
import ImportV2AbortReducer from "./import_v_2_abort_reducer";
import ImportV2BeginReducer from "./import_v_2_begin_reducer";
import ImportV2ChunkReducer from "./import_v_2_chunk_reducer";
import ImportV2CommitReducer from "./import_v_2_commit_reducer";
import InsertComponentReducer from "./insert_component_reducer";
import LogApiCallReducer from "./log_api_call_reducer";
import LoginReducer from "./login_reducer";
import LogoutReducer from "./logout_reducer";
import MigratePageToComponentTreeReducer from "./migrate_page_to_component_tree_reducer";
import MoveComponentReducer from "./move_component_reducer";
import MovePageReducer from "./move_page_reducer";
import PromoteToInstructionReducer from "./promote_to_instruction_reducer";
import PurgePageReducer from "./purge_page_reducer";
import RegisterReducer from "./register_reducer";
import RegisterComponentTypeReducer from "./register_component_type_reducer";
import RenamePropertyReducer from "./rename_property_reducer";
import RenameViewReducer from "./rename_view_reducer";
import ReorderPropertyReducer from "./reorder_property_reducer";
import ReplacePageDocReducer from "./replace_page_doc_reducer";
import RequestPageAccessReducer from "./request_page_access_reducer";
import ResolveBlockCommentReducer from "./resolve_block_comment_reducer";
import ResolvePageAccessRequestReducer from "./resolve_page_access_request_reducer";
import RestoreComponentReducer from "./restore_component_reducer";
import RestorePageReducer from "./restore_page_reducer";
import RestorePageToSnapshotReducer from "./restore_page_to_snapshot_reducer";
import RevokeApiEndpointKeyReducer from "./revoke_api_endpoint_key_reducer";
import RunPendingMigrationsReducer from "./run_pending_migrations_reducer";
import SaveComponentYjsStateReducer from "./save_component_yjs_state_reducer";
import SaveYjsStateReducer from "./save_yjs_state_reducer";
import SeedAgentInstructionPropertyReducer from "./seed_agent_instruction_property_reducer";
import SetBlockAccessRuleReducer from "./set_block_access_rule_reducer";
import SetDefaultViewReducer from "./set_default_view_reducer";
import SetOidcTrustPolicyReducer from "./set_oidc_trust_policy_reducer";
import SetPageAccessRuleReducer from "./set_page_access_rule_reducer";
import SetPageHiddenReducer from "./set_page_hidden_reducer";
import SetPropertyValueReducer from "./set_property_value_reducer";
import SetSchemaParentReducer from "./set_schema_parent_reducer";
import SetUserAdminReducer from "./set_user_admin_reducer";
import SetUserPreferenceReducer from "./set_user_preference_reducer";
import SetUserProfileReducer from "./set_user_profile_reducer";
import SetWorkspaceSettingReducer from "./set_workspace_setting_reducer";
import TakeSnapshotReducer from "./take_snapshot_reducer";
import TakeSnapshotWithContentReducer from "./take_snapshot_with_content_reducer";
import TouchApiEndpointKeyReducer from "./touch_api_endpoint_key_reducer";
import UpdateApiEndpointReducer from "./update_api_endpoint_reducer";
import UpdateApiFieldMappingReducer from "./update_api_field_mapping_reducer";
import UpdateBlockCommentReducer from "./update_block_comment_reducer";
import UpdateComponentPropsReducer from "./update_component_props_reducer";
import UpdateComponentTypeReducer from "./update_component_type_reducer";
import UpdateDatabaseRowReducer from "./update_database_row_reducer";
import UpdateDatabaseSchemaConfigReducer from "./update_database_schema_config_reducer";
import UpdatePageBlocksReducer from "./update_page_blocks_reducer";
import UpdatePageContentReducer from "./update_page_content_reducer";
import UpdatePageIconReducer from "./update_page_icon_reducer";
import UpdatePageTitleReducer from "./update_page_title_reducer";
import UpdatePropertyConfigReducer from "./update_property_config_reducer";
import UpdatePropertyTypeReducer from "./update_property_type_reducer";
import UpdateViewConfigReducer from "./update_view_config_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import ApiCallLogRow from "./api_call_log_table";
import ApiEndpointRow from "./api_endpoint_table";
import ApiEndpointKeyRow from "./api_endpoint_key_table";
import ApiEndpointKeyLookupRow from "./api_endpoint_key_lookup_table";
import ApiFieldMappingRow from "./api_field_mapping_table";
import AttachmentRow from "./attachment_table";
import BlockAccessRuleRow from "./block_access_rule_table";
import BlockCommentRow from "./block_comment_table";
import ComponentNodeRow from "./component_node_table";
import ComponentTypeDefinitionRow from "./component_type_definition_table";
import ComponentYjsStateRow from "./component_yjs_state_table";
import DatabaseRowMarkerRow from "./database_row_marker_table";
import DatabaseSchemaRow from "./database_schema_table";
import DatabaseViewRow from "./database_view_table";
import IdCounterRow from "./id_counter_table";
import LoginResultRow from "./login_result_table";
import MigrationStateRow from "./migration_state_table";
import ModuleInstallMetaRow from "./module_install_meta_table";
import PageRow from "./page_table";
import PageAccessRequestRow from "./page_access_request_table";
import PageAccessRuleRow from "./page_access_rule_table";
import PageContentRow from "./page_content_table";
import PagePropertyValueRow from "./page_property_value_table";
import PagePropertyValueHistoryRow from "./page_property_value_history_table";
import PageSnapshotRow from "./page_snapshot_table";
import PageYjsStateRow from "./page_yjs_state_table";
import PropertyDefinitionRow from "./property_definition_table";
import ReadableComponentsRow from "./readable_components_table";
import ReadablePagesRow from "./readable_pages_table";
import ReadableReviewSnapshotsRow from "./readable_review_snapshots_table";
import ReadableSchemasRow from "./readable_schemas_table";
import UserRow from "./user_table";
import UserPreferenceRow from "./user_preference_table";
import WorkspaceSettingRow from "./workspace_setting_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  api_call_log: __table({
    name: 'api_call_log',
    indexes: [
      { name: 'at', algorithm: 'btree', columns: [
        'at',
      ] },
      { name: 'endpoint_id', algorithm: 'btree', columns: [
        'endpointId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'api_call_log_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ApiCallLogRow),
  api_endpoint: __table({
    name: 'api_endpoint',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'slug', algorithm: 'btree', columns: [
        'slug',
      ] },
    ],
    constraints: [
      { name: 'api_endpoint_id_key', constraint: 'unique', columns: ['id'] },
      { name: 'api_endpoint_slug_key', constraint: 'unique', columns: ['slug'] },
    ],
  }, ApiEndpointRow),
  api_endpoint_key: __table({
    name: 'api_endpoint_key',
    indexes: [
      { name: 'endpoint_id', algorithm: 'btree', columns: [
        'endpointId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'api_endpoint_key_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ApiEndpointKeyRow),
  api_field_mapping: __table({
    name: 'api_field_mapping',
    indexes: [
      { name: 'endpoint_id', algorithm: 'btree', columns: [
        'endpointId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'api_field_mapping_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ApiFieldMappingRow),
  attachment: __table({
    name: 'attachment',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'page_id', algorithm: 'btree', columns: [
        'pageId',
      ] },
    ],
    constraints: [
      { name: 'attachment_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, AttachmentRow),
  block_access_rule: __table({
    name: 'block_access_rule',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'page_id', algorithm: 'btree', columns: [
        'pageId',
      ] },
    ],
    constraints: [
      { name: 'block_access_rule_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, BlockAccessRuleRow),
  block_comment: __table({
    name: 'block_comment',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'page_id', algorithm: 'btree', columns: [
        'pageId',
      ] },
    ],
    constraints: [
      { name: 'block_comment_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, BlockCommentRow),
  component_node: __table({
    name: 'component_node',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'parent_id', algorithm: 'btree', columns: [
        'parentId',
      ] },
      { name: 'surface_id', algorithm: 'btree', columns: [
        'surfaceId',
      ] },
      { name: 'component_node_by_surface_parent', algorithm: 'btree', columns: [
        'surfaceId',
        'parentId',
      ] },
    ],
    constraints: [
      { name: 'component_node_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ComponentNodeRow),
  component_type_definition: __table({
    name: 'component_type_definition',
    indexes: [
      { name: 'component_type', algorithm: 'btree', columns: [
        'componentType',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'component_type_definition_component_type_key', constraint: 'unique', columns: ['componentType'] },
      { name: 'component_type_definition_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ComponentTypeDefinitionRow),
  component_yjs_state: __table({
    name: 'component_yjs_state',
    indexes: [
      { name: 'component_node_id', algorithm: 'btree', columns: [
        'componentNodeId',
      ] },
    ],
    constraints: [
      { name: 'component_yjs_state_component_node_id_key', constraint: 'unique', columns: ['componentNodeId'] },
    ],
  }, ComponentYjsStateRow),
  database_row_marker: __table({
    name: 'database_row_marker',
    indexes: [
      { name: 'client_request_id', algorithm: 'btree', columns: [
        'clientRequestId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'page_id', algorithm: 'btree', columns: [
        'pageId',
      ] },
    ],
    constraints: [
      { name: 'database_row_marker_client_request_id_key', constraint: 'unique', columns: ['clientRequestId'] },
      { name: 'database_row_marker_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, DatabaseRowMarkerRow),
  database_schema: __table({
    name: 'database_schema',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'page_id', algorithm: 'btree', columns: [
        'pageId',
      ] },
    ],
    constraints: [
      { name: 'database_schema_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, DatabaseSchemaRow),
  database_view: __table({
    name: 'database_view',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'page_id', algorithm: 'btree', columns: [
        'pageId',
      ] },
    ],
    constraints: [
      { name: 'database_view_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, DatabaseViewRow),
  id_counter: __table({
    name: 'id_counter',
    indexes: [
      { name: 'name', algorithm: 'btree', columns: [
        'name',
      ] },
    ],
    constraints: [
      { name: 'id_counter_name_key', constraint: 'unique', columns: ['name'] },
    ],
  }, IdCounterRow),
  login_result: __table({
    name: 'login_result',
    indexes: [
      { name: 'identity', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'login_result_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, LoginResultRow),
  migration_state: __table({
    name: 'migration_state',
    indexes: [
      { name: 'key', algorithm: 'btree', columns: [
        'key',
      ] },
    ],
    constraints: [
      { name: 'migration_state_key_key', constraint: 'unique', columns: ['key'] },
    ],
  }, MigrationStateRow),
  module_install_meta: __table({
    name: 'module_install_meta',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'module_install_meta_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ModuleInstallMetaRow),
  page: __table({
    name: 'page',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'parent_id', algorithm: 'btree', columns: [
        'parentId',
      ] },
      { name: 'parent_pk', algorithm: 'btree', columns: [
        'parentPk',
      ] },
    ],
    constraints: [
      { name: 'page_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PageRow),
  page_access_request: __table({
    name: 'page_access_request',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'page_id', algorithm: 'btree', columns: [
        'pageId',
      ] },
    ],
    constraints: [
      { name: 'page_access_request_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PageAccessRequestRow),
  page_access_rule: __table({
    name: 'page_access_rule',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'page_id', algorithm: 'btree', columns: [
        'pageId',
      ] },
    ],
    constraints: [
      { name: 'page_access_rule_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PageAccessRuleRow),
  page_content: __table({
    name: 'page_content',
    indexes: [
      { name: 'page_id', algorithm: 'btree', columns: [
        'pageId',
      ] },
    ],
    constraints: [
      { name: 'page_content_page_id_key', constraint: 'unique', columns: ['pageId'] },
    ],
  }, PageContentRow),
  page_property_value: __table({
    name: 'page_property_value',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'page_id', algorithm: 'btree', columns: [
        'pageId',
      ] },
      { name: 'property_definition_id', algorithm: 'btree', columns: [
        'propertyDefinitionId',
      ] },
    ],
    constraints: [
      { name: 'page_property_value_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PagePropertyValueRow),
  page_property_value_history: __table({
    name: 'page_property_value_history',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'page_id', algorithm: 'btree', columns: [
        'pageId',
      ] },
      { name: 'property_definition_id', algorithm: 'btree', columns: [
        'propertyDefinitionId',
      ] },
    ],
    constraints: [
      { name: 'page_property_value_history_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PagePropertyValueHistoryRow),
  page_snapshot: __table({
    name: 'page_snapshot',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'page_id', algorithm: 'btree', columns: [
        'pageId',
      ] },
    ],
    constraints: [
      { name: 'page_snapshot_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PageSnapshotRow),
  page_yjs_state: __table({
    name: 'page_yjs_state',
    indexes: [
      { name: 'page_id', algorithm: 'btree', columns: [
        'pageId',
      ] },
    ],
    constraints: [
      { name: 'page_yjs_state_page_id_key', constraint: 'unique', columns: ['pageId'] },
    ],
  }, PageYjsStateRow),
  property_definition: __table({
    name: 'property_definition',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'schema_id', algorithm: 'btree', columns: [
        'schemaId',
      ] },
    ],
    constraints: [
      { name: 'property_definition_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PropertyDefinitionRow),
  user: __table({
    name: 'user',
    indexes: [
      { name: 'identity', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'user_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, UserRow),
  user_preference: __table({
    name: 'user_preference',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'identity', algorithm: 'btree', columns: [
        'identity',
      ] },
      { name: 'user_preference_identity_key', algorithm: 'btree', columns: [
        'identity',
        'key',
      ] },
    ],
    constraints: [
      { name: 'user_preference_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, UserPreferenceRow),
  workspace_setting: __table({
    name: 'workspace_setting',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'key', algorithm: 'btree', columns: [
        'key',
      ] },
    ],
    constraints: [
      { name: 'workspace_setting_id_key', constraint: 'unique', columns: ['id'] },
      { name: 'workspace_setting_key_key', constraint: 'unique', columns: ['key'] },
    ],
  }, WorkspaceSettingRow),
  api_endpoint_key_lookup: __table({
    name: 'api_endpoint_key_lookup',
    indexes: [
    ],
    constraints: [
    ],
  }, ApiEndpointKeyLookupRow),
  readable_components: __table({
    name: 'readable_components',
    indexes: [
    ],
    constraints: [
    ],
  }, ReadableComponentsRow),
  readable_pages: __table({
    name: 'readable_pages',
    indexes: [
    ],
    constraints: [
    ],
  }, ReadablePagesRow),
  readable_review_snapshots: __table({
    name: 'readable_review_snapshots',
    indexes: [
    ],
    constraints: [
    ],
  }, ReadableReviewSnapshotsRow),
  readable_schemas: __table({
    name: 'readable_schemas',
    indexes: [
    ],
    constraints: [
    ],
  }, ReadableSchemasRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("add_property", AddPropertyReducer),
  __reducerSchema("append_page_doc", AppendPageDocReducer),
  __reducerSchema("authorize_blob_access", AuthorizeBlobAccessReducer),
  __reducerSchema("clear_block_access_rule", ClearBlockAccessRuleReducer),
  __reducerSchema("clear_page_access_rule", ClearPageAccessRuleReducer),
  __reducerSchema("clear_property_value", ClearPropertyValueReducer),
  __reducerSchema("create_api_endpoint", CreateApiEndpointReducer),
  __reducerSchema("create_api_endpoint_key", CreateApiEndpointKeyReducer),
  __reducerSchema("create_api_field_mapping", CreateApiFieldMappingReducer),
  __reducerSchema("create_attachment", CreateAttachmentReducer),
  __reducerSchema("create_block_comment", CreateBlockCommentReducer),
  __reducerSchema("create_component_tree_page", CreateComponentTreePageReducer),
  __reducerSchema("create_database_row", CreateDatabaseRowReducer),
  __reducerSchema("create_database_schema", CreateDatabaseSchemaReducer),
  __reducerSchema("create_local_user", CreateLocalUserReducer),
  __reducerSchema("create_page", CreatePageReducer),
  __reducerSchema("create_view", CreateViewReducer),
  __reducerSchema("delete_api_endpoint", DeleteApiEndpointReducer),
  __reducerSchema("delete_api_field_mapping", DeleteApiFieldMappingReducer),
  __reducerSchema("delete_attachment", DeleteAttachmentReducer),
  __reducerSchema("delete_block_comment", DeleteBlockCommentReducer),
  __reducerSchema("delete_component", DeleteComponentReducer),
  __reducerSchema("delete_database_row", DeleteDatabaseRowReducer),
  __reducerSchema("delete_page", DeletePageReducer),
  __reducerSchema("delete_page_subtree", DeletePageSubtreeReducer),
  __reducerSchema("delete_property", DeletePropertyReducer),
  __reducerSchema("delete_view", DeleteViewReducer),
  __reducerSchema("empty_trash", EmptyTrashReducer),
  __reducerSchema("harden_local_passwords", HardenLocalPasswordsReducer),
  __reducerSchema("import_v_2_abort", ImportV2AbortReducer),
  __reducerSchema("import_v_2_begin", ImportV2BeginReducer),
  __reducerSchema("import_v_2_chunk", ImportV2ChunkReducer),
  __reducerSchema("import_v_2_commit", ImportV2CommitReducer),
  __reducerSchema("insert_component", InsertComponentReducer),
  __reducerSchema("log_api_call", LogApiCallReducer),
  __reducerSchema("login", LoginReducer),
  __reducerSchema("logout", LogoutReducer),
  __reducerSchema("migrate_page_to_component_tree", MigratePageToComponentTreeReducer),
  __reducerSchema("move_component", MoveComponentReducer),
  __reducerSchema("move_page", MovePageReducer),
  __reducerSchema("promote_to_instruction", PromoteToInstructionReducer),
  __reducerSchema("purge_page", PurgePageReducer),
  __reducerSchema("register", RegisterReducer),
  __reducerSchema("register_component_type", RegisterComponentTypeReducer),
  __reducerSchema("rename_property", RenamePropertyReducer),
  __reducerSchema("rename_view", RenameViewReducer),
  __reducerSchema("reorder_property", ReorderPropertyReducer),
  __reducerSchema("replace_page_doc", ReplacePageDocReducer),
  __reducerSchema("request_page_access", RequestPageAccessReducer),
  __reducerSchema("resolve_block_comment", ResolveBlockCommentReducer),
  __reducerSchema("resolve_page_access_request", ResolvePageAccessRequestReducer),
  __reducerSchema("restore_component", RestoreComponentReducer),
  __reducerSchema("restore_page", RestorePageReducer),
  __reducerSchema("restore_page_to_snapshot", RestorePageToSnapshotReducer),
  __reducerSchema("revoke_api_endpoint_key", RevokeApiEndpointKeyReducer),
  __reducerSchema("run_pending_migrations", RunPendingMigrationsReducer),
  __reducerSchema("save_component_yjs_state", SaveComponentYjsStateReducer),
  __reducerSchema("save_yjs_state", SaveYjsStateReducer),
  __reducerSchema("seed_agent_instruction_property", SeedAgentInstructionPropertyReducer),
  __reducerSchema("set_block_access_rule", SetBlockAccessRuleReducer),
  __reducerSchema("set_default_view", SetDefaultViewReducer),
  __reducerSchema("set_oidc_trust_policy", SetOidcTrustPolicyReducer),
  __reducerSchema("set_page_access_rule", SetPageAccessRuleReducer),
  __reducerSchema("set_page_hidden", SetPageHiddenReducer),
  __reducerSchema("set_property_value", SetPropertyValueReducer),
  __reducerSchema("set_schema_parent", SetSchemaParentReducer),
  __reducerSchema("set_user_admin", SetUserAdminReducer),
  __reducerSchema("set_user_preference", SetUserPreferenceReducer),
  __reducerSchema("set_user_profile", SetUserProfileReducer),
  __reducerSchema("set_workspace_setting", SetWorkspaceSettingReducer),
  __reducerSchema("take_snapshot", TakeSnapshotReducer),
  __reducerSchema("take_snapshot_with_content", TakeSnapshotWithContentReducer),
  __reducerSchema("touch_api_endpoint_key", TouchApiEndpointKeyReducer),
  __reducerSchema("update_api_endpoint", UpdateApiEndpointReducer),
  __reducerSchema("update_api_field_mapping", UpdateApiFieldMappingReducer),
  __reducerSchema("update_block_comment", UpdateBlockCommentReducer),
  __reducerSchema("update_component_props", UpdateComponentPropsReducer),
  __reducerSchema("update_component_type", UpdateComponentTypeReducer),
  __reducerSchema("update_database_row", UpdateDatabaseRowReducer),
  __reducerSchema("update_database_schema_config", UpdateDatabaseSchemaConfigReducer),
  __reducerSchema("update_page_blocks", UpdatePageBlocksReducer),
  __reducerSchema("update_page_content", UpdatePageContentReducer),
  __reducerSchema("update_page_icon", UpdatePageIconReducer),
  __reducerSchema("update_page_title", UpdatePageTitleReducer),
  __reducerSchema("update_property_config", UpdatePropertyConfigReducer),
  __reducerSchema("update_property_type", UpdatePropertyTypeReducer),
  __reducerSchema("update_view_config", UpdateViewConfigReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.0.3" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

