// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.10.1 (commit 3d7607082ab47257adeb7c25164536511237f2b5).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AddPropertyReducer from "./add_property_reducer";
import AppendPageDocReducer from "./append_page_doc_reducer";
import ClearBlockAccessRuleReducer from "./clear_block_access_rule_reducer";
import ClearPageAccessRuleReducer from "./clear_page_access_rule_reducer";
import ClearPropertyValueReducer from "./clear_property_value_reducer";
import CreateApiEndpointReducer from "./create_api_endpoint_reducer";
import CreateApiEndpointKeyReducer from "./create_api_endpoint_key_reducer";
import CreateApiFieldMappingReducer from "./create_api_field_mapping_reducer";
import CreateAttachmentReducer from "./create_attachment_reducer";
import CreateComponentTreePageReducer from "./create_component_tree_page_reducer";
import CreateDatabaseRowReducer from "./create_database_row_reducer";
import CreateDatabaseSchemaReducer from "./create_database_schema_reducer";
import CreateLocalUserReducer from "./create_local_user_reducer";
import CreatePageReducer from "./create_page_reducer";
import CreateViewReducer from "./create_view_reducer";
import DeleteApiEndpointReducer from "./delete_api_endpoint_reducer";
import DeleteApiFieldMappingReducer from "./delete_api_field_mapping_reducer";
import DeleteAttachmentReducer from "./delete_attachment_reducer";
import DeleteComponentReducer from "./delete_component_reducer";
import DeleteDatabaseRowReducer from "./delete_database_row_reducer";
import DeletePageReducer from "./delete_page_reducer";
import DeletePageSubtreeReducer from "./delete_page_subtree_reducer";
import DeletePropertyReducer from "./delete_property_reducer";
import DeleteViewReducer from "./delete_view_reducer";
import EmptyTrashReducer from "./empty_trash_reducer";
import HardenLocalPasswordsReducer from "./harden_local_passwords_reducer";
import ImportV2AbortReducer from "./import_v_2_abort_reducer";
import ImportV2BeginReducer from "./import_v_2_begin_reducer";
import ImportV2ChunkReducer from "./import_v_2_chunk_reducer";
import ImportV2CommitReducer from "./import_v_2_commit_reducer";
import InsertComponentReducer from "./insert_component_reducer";
import LogApiCallReducer from "./log_api_call_reducer";
import LoginReducer from "./login_reducer";
import LogoutReducer from "./logout_reducer";
import MigratePageToComponentTreeReducer from "./migrate_page_to_component_tree_reducer";
import MoveComponentReducer from "./move_component_reducer";
import MovePageReducer from "./move_page_reducer";
import PromoteToInstructionReducer from "./promote_to_instruction_reducer";
import PurgePageReducer from "./purge_page_reducer";
import RegisterReducer from "./register_reducer";
import RegisterComponentTypeReducer from "./register_component_type_reducer";
import RenamePropertyReducer from "./rename_property_reducer";
import RenameViewReducer from "./rename_view_reducer";
import ReorderPropertyReducer from "./reorder_property_reducer";
import ReplacePageDocReducer from "./replace_page_doc_reducer";
import RequestPageAccessReducer from "./request_page_access_reducer";
import ResolvePageAccessRequestReducer from "./resolve_page_access_request_reducer";
import RestoreComponentReducer from "./restore_component_reducer";
import RestorePageReducer from "./restore_page_reducer";
import RestorePageToSnapshotReducer from "./restore_page_to_snapshot_reducer";
import RevokeApiEndpointKeyReducer from "./revoke_api_endpoint_key_reducer";
import RunPendingMigrationsReducer from "./run_pending_migrations_reducer";
import SaveComponentYjsStateReducer from "./save_component_yjs_state_reducer";
import SaveYjsStateReducer from "./save_yjs_state_reducer";
import SeedAgentInstructionPropertyReducer from "./seed_agent_instruction_property_reducer";
import SetBlockAccessRuleReducer from "./set_block_access_rule_reducer";
import SetDefaultViewReducer from "./set_default_view_reducer";
import SetOidcTrustPolicyReducer from "./set_oidc_trust_policy_reducer";
import SetPageAccessRuleReducer from "./set_page_access_rule_reducer";
import SetPageHiddenReducer from "./set_page_hidden_reducer";
import SetPropertyValueReducer from "./set_property_value_reducer";
import SetSchemaParentReducer from "./set_schema_parent_reducer";
import SetUserAdminReducer from "./set_user_admin_reducer";
import SetUserPreferenceReducer from "./set_user_preference_reducer";
import SetUserProfileReducer from "./set_user_profile_reducer";
import SetWorkspaceSettingReducer from "./set_workspace_setting_reducer";
import TakeSnapshotReducer from "./take_snapshot_reducer";
import TakeSnapshotWithContentReducer from "./take_snapshot_with_content_reducer";
import TouchApiEndpointKeyReducer from "./touch_api_endpoint_key_reducer";
import UpdateApiEndpointReducer from "./update_api_endpoint_reducer";
import UpdateApiFieldMappingReducer from "./update_api_field_mapping_reducer";
import UpdateComponentPropsReducer from "./update_component_props_reducer";
import UpdateComponentTypeReducer from "./update_component_type_reducer";
import UpdateDatabaseRowReducer from "./update_database_row_reducer";
import UpdateDatabaseSchemaConfigReducer from "./update_database_schema_config_reducer";
import UpdatePageBlocksReducer from "./update_page_blocks_reducer";
import UpdatePageContentReducer from "./update_page_content_reducer";
import UpdatePageIconReducer from "./update_page_icon_reducer";
import UpdatePageTitleReducer from "./update_page_title_reducer";
import UpdatePropertyConfigReducer from "./update_property_config_reducer";
import UpdatePropertyTypeReducer from "./update_property_type_reducer";
import UpdateViewConfigReducer from "./update_view_config_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import ApiCallLogRow from "./api_call_log_table";
import ApiEndpointRow from "./api_endpoint_table";
import ApiEndpointKeyRow from "./api_endpoint_key_table";
import ApiEndpointKeyLookupRow from "./api_endpoint_key_lookup_table";
import ApiFieldMappingRow from "./api_field_mapping_table";
import AttachmentRow from "./attachment_table";
import BlockAccessRuleRow from "./block_access_rule_table";
import ComponentNodeRow from "./component_node_table";
import ComponentTypeDefinitionRow from "./component_type_definition_table";
import ComponentYjsStateRow from "./component_yjs_state_table";
import DatabaseRowMarkerRow from "./database_row_marker_table";
import DatabaseSchemaRow from "./database_schema_table";
import DatabaseViewRow from "./database_view_table";
import IdCounterRow from "./id_counter_table";
import LoginResultRow from "./login_result_table";
import MigrationStateRow from "./migration_state_table";
import ModuleInstallMetaRow from "./module_install_meta_table";
import PageRow from "./page_table";
import PageAccessRequestRow from "./page_access_request_table";
import PageAccessRuleRow from "./page_access_rule_table";
import PageContentRow from "./page_content_table";
import PagePropertyValueRow from "./page_property_value_table";
import PagePropertyValueHistoryRow from "./page_property_value_history_table";
import PageSnapshotRow from "./page_snapshot_table";
import PageYjsStateRow from "./page_yjs_state_table";
import PropertyDefinitionRow from "./property_definition_table";
import ReadableComponentsRow from "./readable_components_table";
import ReadablePagesRow from "./readable_pages_table";
import ReadableReviewSnapshotsRow from "./readable_review_snapshots_table";
import ReadableSchemasRow from "./readable_schemas_table";
import UserRow from "./user_table";
import UserPreferenceRow from "./user_preference_table";
import WorkspaceSettingRow from "./workspace_setting_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  apiCallLog: __table({
    name: 'api_call_log',
    indexes: [
      { accessor: 'at', name: 'api_call_log_at_idx_btree', algorithm: 'btree', columns: [
        'at',
      ] },
      { accessor: 'endpoint_id', name: 'api_call_log_endpoint_id_idx_btree', algorithm: 'btree', columns: [
        'endpointId',
      ] },
      { accessor: 'id', name: 'api_call_log_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'api_call_log_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ApiCallLogRow),
  apiEndpoint: __table({
    name: 'api_endpoint',
    indexes: [
      { accessor: 'id', name: 'api_endpoint_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'slug', name: 'api_endpoint_slug_idx_btree', algorithm: 'btree', columns: [
        'slug',
      ] },
    ],
    constraints: [
      { name: 'api_endpoint_id_key', constraint: 'unique', columns: ['id'] },
      { name: 'api_endpoint_slug_key', constraint: 'unique', columns: ['slug'] },
    ],
  }, ApiEndpointRow),
  apiEndpointKey: __table({
    name: 'api_endpoint_key',
    indexes: [
      { accessor: 'endpoint_id', name: 'api_endpoint_key_endpoint_id_idx_btree', algorithm: 'btree', columns: [
        'endpointId',
      ] },
      { accessor: 'id', name: 'api_endpoint_key_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'api_endpoint_key_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ApiEndpointKeyRow),
  apiFieldMapping: __table({
    name: 'api_field_mapping',
    indexes: [
      { accessor: 'endpoint_id', name: 'api_field_mapping_endpoint_id_idx_btree', algorithm: 'btree', columns: [
        'endpointId',
      ] },
      { accessor: 'id', name: 'api_field_mapping_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'api_field_mapping_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ApiFieldMappingRow),
  attachment: __table({
    name: 'attachment',
    indexes: [
      { accessor: 'id', name: 'attachment_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'page_id', name: 'attachment_page_id_idx_btree', algorithm: 'btree', columns: [
        'pageId',
      ] },
    ],
    constraints: [
      { name: 'attachment_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, AttachmentRow),
  blockAccessRule: __table({
    name: 'block_access_rule',
    indexes: [
      { accessor: 'id', name: 'block_access_rule_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'page_id', name: 'block_access_rule_page_id_idx_btree', algorithm: 'btree', columns: [
        'pageId',
      ] },
    ],
    constraints: [
      { name: 'block_access_rule_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, BlockAccessRuleRow),
  componentNode: __table({
    name: 'component_node',
    indexes: [
      { accessor: 'id', name: 'component_node_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'parent_id', name: 'component_node_parent_id_idx_btree', algorithm: 'btree', columns: [
        'parentId',
      ] },
      { accessor: 'surface_id', name: 'component_node_surface_id_idx_btree', algorithm: 'btree', columns: [
        'surfaceId',
      ] },
      { accessor: 'component_node_by_surface_parent', name: 'component_node_surface_id_parent_id_idx_btree', algorithm: 'btree', columns: [
        'surfaceId',
        'parentId',
      ] },
    ],
    constraints: [
      { name: 'component_node_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ComponentNodeRow),
  componentTypeDefinition: __table({
    name: 'component_type_definition',
    indexes: [
      { accessor: 'component_type', name: 'component_type_definition_component_type_idx_btree', algorithm: 'btree', columns: [
        'componentType',
      ] },
      { accessor: 'id', name: 'component_type_definition_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'component_type_definition_component_type_key', constraint: 'unique', columns: ['componentType'] },
      { name: 'component_type_definition_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ComponentTypeDefinitionRow),
  componentYjsState: __table({
    name: 'component_yjs_state',
    indexes: [
      { accessor: 'component_node_id', name: 'component_yjs_state_component_node_id_idx_btree', algorithm: 'btree', columns: [
        'componentNodeId',
      ] },
    ],
    constraints: [
      { name: 'component_yjs_state_component_node_id_key', constraint: 'unique', columns: ['componentNodeId'] },
    ],
  }, ComponentYjsStateRow),
  databaseRowMarker: __table({
    name: 'database_row_marker',
    indexes: [
      { accessor: 'client_request_id', name: 'database_row_marker_client_request_id_idx_btree', algorithm: 'btree', columns: [
        'clientRequestId',
      ] },
      { accessor: 'id', name: 'database_row_marker_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'page_id', name: 'database_row_marker_page_id_idx_btree', algorithm: 'btree', columns: [
        'pageId',
      ] },
    ],
    constraints: [
      { name: 'database_row_marker_client_request_id_key', constraint: 'unique', columns: ['clientRequestId'] },
      { name: 'database_row_marker_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, DatabaseRowMarkerRow),
  databaseSchema: __table({
    name: 'database_schema',
    indexes: [
      { accessor: 'id', name: 'database_schema_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'page_id', name: 'database_schema_page_id_idx_btree', algorithm: 'btree', columns: [
        'pageId',
      ] },
    ],
    constraints: [
      { name: 'database_schema_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, DatabaseSchemaRow),
  databaseView: __table({
    name: 'database_view',
    indexes: [
      { accessor: 'id', name: 'database_view_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'page_id', name: 'database_view_page_id_idx_btree', algorithm: 'btree', columns: [
        'pageId',
      ] },
    ],
    constraints: [
      { name: 'database_view_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, DatabaseViewRow),
  idCounter: __table({
    name: 'id_counter',
    indexes: [
      { accessor: 'name', name: 'id_counter_name_idx_btree', algorithm: 'btree', columns: [
        'name',
      ] },
    ],
    constraints: [
      { name: 'id_counter_name_key', constraint: 'unique', columns: ['name'] },
    ],
  }, IdCounterRow),
  loginResult: __table({
    name: 'login_result',
    indexes: [
      { accessor: 'identity', name: 'login_result_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'login_result_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, LoginResultRow),
  migrationState: __table({
    name: 'migration_state',
    indexes: [
      { accessor: 'key', name: 'migration_state_key_idx_btree', algorithm: 'btree', columns: [
        'key',
      ] },
    ],
    constraints: [
      { name: 'migration_state_key_key', constraint: 'unique', columns: ['key'] },
    ],
  }, MigrationStateRow),
  moduleInstallMeta: __table({
    name: 'module_install_meta',
    indexes: [
      { accessor: 'id', name: 'module_install_meta_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'module_install_meta_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ModuleInstallMetaRow),
  page: __table({
    name: 'page',
    indexes: [
      { accessor: 'id', name: 'page_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'parent_id', name: 'page_parent_id_idx_btree', algorithm: 'btree', columns: [
        'parentId',
      ] },
      { accessor: 'parent_pk', name: 'page_parent_pk_idx_btree', algorithm: 'btree', columns: [
        'parentPk',
      ] },
    ],
    constraints: [
      { name: 'page_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PageRow),
  pageAccessRequest: __table({
    name: 'page_access_request',
    indexes: [
      { accessor: 'id', name: 'page_access_request_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'page_id', name: 'page_access_request_page_id_idx_btree', algorithm: 'btree', columns: [
        'pageId',
      ] },
    ],
    constraints: [
      { name: 'page_access_request_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PageAccessRequestRow),
  pageAccessRule: __table({
    name: 'page_access_rule',
    indexes: [
      { accessor: 'id', name: 'page_access_rule_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'page_id', name: 'page_access_rule_page_id_idx_btree', algorithm: 'btree', columns: [
        'pageId',
      ] },
    ],
    constraints: [
      { name: 'page_access_rule_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PageAccessRuleRow),
  pageContent: __table({
    name: 'page_content',
    indexes: [
      { accessor: 'page_id', name: 'page_content_page_id_idx_btree', algorithm: 'btree', columns: [
        'pageId',
      ] },
    ],
    constraints: [
      { name: 'page_content_page_id_key', constraint: 'unique', columns: ['pageId'] },
    ],
  }, PageContentRow),
  pagePropertyValue: __table({
    name: 'page_property_value',
    indexes: [
      { accessor: 'id', name: 'page_property_value_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'page_id', name: 'page_property_value_page_id_idx_btree', algorithm: 'btree', columns: [
        'pageId',
      ] },
      { accessor: 'property_definition_id', name: 'page_property_value_property_definition_id_idx_btree', algorithm: 'btree', columns: [
        'propertyDefinitionId',
      ] },
    ],
    constraints: [
      { name: 'page_property_value_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PagePropertyValueRow),
  pagePropertyValueHistory: __table({
    name: 'page_property_value_history',
    indexes: [
      { accessor: 'id', name: 'page_property_value_history_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'page_id', name: 'page_property_value_history_page_id_idx_btree', algorithm: 'btree', columns: [
        'pageId',
      ] },
      { accessor: 'property_definition_id', name: 'page_property_value_history_property_definition_id_idx_btree', algorithm: 'btree', columns: [
        'propertyDefinitionId',
      ] },
    ],
    constraints: [
      { name: 'page_property_value_history_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PagePropertyValueHistoryRow),
  pageSnapshot: __table({
    name: 'page_snapshot',
    indexes: [
      { accessor: 'id', name: 'page_snapshot_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'page_id', name: 'page_snapshot_page_id_idx_btree', algorithm: 'btree', columns: [
        'pageId',
      ] },
    ],
    constraints: [
      { name: 'page_snapshot_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PageSnapshotRow),
  pageYjsState: __table({
    name: 'page_yjs_state',
    indexes: [
      { accessor: 'page_id', name: 'page_yjs_state_page_id_idx_btree', algorithm: 'btree', columns: [
        'pageId',
      ] },
    ],
    constraints: [
      { name: 'page_yjs_state_page_id_key', constraint: 'unique', columns: ['pageId'] },
    ],
  }, PageYjsStateRow),
  propertyDefinition: __table({
    name: 'property_definition',
    indexes: [
      { accessor: 'id', name: 'property_definition_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'schema_id', name: 'property_definition_schema_id_idx_btree', algorithm: 'btree', columns: [
        'schemaId',
      ] },
    ],
    constraints: [
      { name: 'property_definition_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PropertyDefinitionRow),
  user: __table({
    name: 'user',
    indexes: [
      { accessor: 'identity', name: 'user_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'user_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, UserRow),
  userPreference: __table({
    name: 'user_preference',
    indexes: [
      { accessor: 'id', name: 'user_preference_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'identity', name: 'user_preference_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
      { accessor: 'user_preference_identity_key', name: 'user_preference_identity_key_idx_btree', algorithm: 'btree', columns: [
        'identity',
        'key',
      ] },
    ],
    constraints: [
      { name: 'user_preference_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, UserPreferenceRow),
  workspaceSetting: __table({
    name: 'workspace_setting',
    indexes: [
      { accessor: 'id', name: 'workspace_setting_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'key', name: 'workspace_setting_key_idx_btree', algorithm: 'btree', columns: [
        'key',
      ] },
    ],
    constraints: [
      { name: 'workspace_setting_id_key', constraint: 'unique', columns: ['id'] },
      { name: 'workspace_setting_key_key', constraint: 'unique', columns: ['key'] },
    ],
  }, WorkspaceSettingRow),
  apiEndpointKeyLookup: __table({
    name: 'api_endpoint_key_lookup',
    indexes: [
    ],
    constraints: [
    ],
  }, ApiEndpointKeyLookupRow),
  readableComponents: __table({
    name: 'readable_components',
    indexes: [
    ],
    constraints: [
    ],
  }, ReadableComponentsRow),
  readablePages: __table({
    name: 'readable_pages',
    indexes: [
    ],
    constraints: [
    ],
  }, ReadablePagesRow),
  readableReviewSnapshots: __table({
    name: 'readable_review_snapshots',
    indexes: [
    ],
    constraints: [
    ],
  }, ReadableReviewSnapshotsRow),
  readableSchemas: __table({
    name: 'readable_schemas',
    indexes: [
    ],
    constraints: [
    ],
  }, ReadableSchemasRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("add_property", AddPropertyReducer),
  __reducerSchema("append_page_doc", AppendPageDocReducer),
  __reducerSchema("clear_block_access_rule", ClearBlockAccessRuleReducer),
  __reducerSchema("clear_page_access_rule", ClearPageAccessRuleReducer),
  __reducerSchema("clear_property_value", ClearPropertyValueReducer),
  __reducerSchema("create_api_endpoint", CreateApiEndpointReducer),
  __reducerSchema("create_api_endpoint_key", CreateApiEndpointKeyReducer),
  __reducerSchema("create_api_field_mapping", CreateApiFieldMappingReducer),
  __reducerSchema("create_attachment", CreateAttachmentReducer),
  __reducerSchema("create_component_tree_page", CreateComponentTreePageReducer),
  __reducerSchema("create_database_row", CreateDatabaseRowReducer),
  __reducerSchema("create_database_schema", CreateDatabaseSchemaReducer),
  __reducerSchema("create_local_user", CreateLocalUserReducer),
  __reducerSchema("create_page", CreatePageReducer),
  __reducerSchema("create_view", CreateViewReducer),
  __reducerSchema("delete_api_endpoint", DeleteApiEndpointReducer),
  __reducerSchema("delete_api_field_mapping", DeleteApiFieldMappingReducer),
  __reducerSchema("delete_attachment", DeleteAttachmentReducer),
  __reducerSchema("delete_component", DeleteComponentReducer),
  __reducerSchema("delete_database_row", DeleteDatabaseRowReducer),
  __reducerSchema("delete_page", DeletePageReducer),
  __reducerSchema("delete_page_subtree", DeletePageSubtreeReducer),
  __reducerSchema("delete_property", DeletePropertyReducer),
  __reducerSchema("delete_view", DeleteViewReducer),
  __reducerSchema("empty_trash", EmptyTrashReducer),
  __reducerSchema("harden_local_passwords", HardenLocalPasswordsReducer),
  __reducerSchema("import_v_2_abort", ImportV2AbortReducer),
  __reducerSchema("import_v_2_begin", ImportV2BeginReducer),
  __reducerSchema("import_v_2_chunk", ImportV2ChunkReducer),
  __reducerSchema("import_v_2_commit", ImportV2CommitReducer),
  __reducerSchema("insert_component", InsertComponentReducer),
  __reducerSchema("log_api_call", LogApiCallReducer),
  __reducerSchema("login", LoginReducer),
  __reducerSchema("logout", LogoutReducer),
  __reducerSchema("migrate_page_to_component_tree", MigratePageToComponentTreeReducer),
  __reducerSchema("move_component", MoveComponentReducer),
  __reducerSchema("move_page", MovePageReducer),
  __reducerSchema("promote_to_instruction", PromoteToInstructionReducer),
  __reducerSchema("purge_page", PurgePageReducer),
  __reducerSchema("register", RegisterReducer),
  __reducerSchema("register_component_type", RegisterComponentTypeReducer),
  __reducerSchema("rename_property", RenamePropertyReducer),
  __reducerSchema("rename_view", RenameViewReducer),
  __reducerSchema("reorder_property", ReorderPropertyReducer),
  __reducerSchema("replace_page_doc", ReplacePageDocReducer),
  __reducerSchema("request_page_access", RequestPageAccessReducer),
  __reducerSchema("resolve_page_access_request", ResolvePageAccessRequestReducer),
  __reducerSchema("restore_component", RestoreComponentReducer),
  __reducerSchema("restore_page", RestorePageReducer),
  __reducerSchema("restore_page_to_snapshot", RestorePageToSnapshotReducer),
  __reducerSchema("revoke_api_endpoint_key", RevokeApiEndpointKeyReducer),
  __reducerSchema("run_pending_migrations", RunPendingMigrationsReducer),
  __reducerSchema("save_component_yjs_state", SaveComponentYjsStateReducer),
  __reducerSchema("save_yjs_state", SaveYjsStateReducer),
  __reducerSchema("seed_agent_instruction_property", SeedAgentInstructionPropertyReducer),
  __reducerSchema("set_block_access_rule", SetBlockAccessRuleReducer),
  __reducerSchema("set_default_view", SetDefaultViewReducer),
  __reducerSchema("set_oidc_trust_policy", SetOidcTrustPolicyReducer),
  __reducerSchema("set_page_access_rule", SetPageAccessRuleReducer),
  __reducerSchema("set_page_hidden", SetPageHiddenReducer),
  __reducerSchema("set_property_value", SetPropertyValueReducer),
  __reducerSchema("set_schema_parent", SetSchemaParentReducer),
  __reducerSchema("set_user_admin", SetUserAdminReducer),
  __reducerSchema("set_user_preference", SetUserPreferenceReducer),
  __reducerSchema("set_user_profile", SetUserProfileReducer),
  __reducerSchema("set_workspace_setting", SetWorkspaceSettingReducer),
  __reducerSchema("take_snapshot", TakeSnapshotReducer),
  __reducerSchema("take_snapshot_with_content", TakeSnapshotWithContentReducer),
  __reducerSchema("touch_api_endpoint_key", TouchApiEndpointKeyReducer),
  __reducerSchema("update_api_endpoint", UpdateApiEndpointReducer),
  __reducerSchema("update_api_field_mapping", UpdateApiFieldMappingReducer),
  __reducerSchema("update_component_props", UpdateComponentPropsReducer),
  __reducerSchema("update_component_type", UpdateComponentTypeReducer),
  __reducerSchema("update_database_row", UpdateDatabaseRowReducer),
  __reducerSchema("update_database_schema_config", UpdateDatabaseSchemaConfigReducer),
  __reducerSchema("update_page_blocks", UpdatePageBlocksReducer),
  __reducerSchema("update_page_content", UpdatePageContentReducer),
  __reducerSchema("update_page_icon", UpdatePageIconReducer),
  __reducerSchema("update_page_title", UpdatePageTitleReducer),
  __reducerSchema("update_property_config", UpdatePropertyConfigReducer),
  __reducerSchema("update_property_type", UpdatePropertyTypeReducer),
  __reducerSchema("update_view_config", UpdateViewConfigReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

type __SchemaWithTableAccessorAliases = Omit<typeof tablesSchema.schemaType, "tables"> & {
  tables: typeof tablesSchema.schemaType.tables & {
    /** @deprecated Use `apiCallLog` instead. This alias will be removed in the next major version. */
    readonly "api_call_log": Omit<typeof tablesSchema.schemaType.tables["apiCallLog"], "accessorName"> & { readonly accessorName: "api_call_log" };
    /** @deprecated Use `apiEndpoint` instead. This alias will be removed in the next major version. */
    readonly "api_endpoint": Omit<typeof tablesSchema.schemaType.tables["apiEndpoint"], "accessorName"> & { readonly accessorName: "api_endpoint" };
    /** @deprecated Use `apiEndpointKey` instead. This alias will be removed in the next major version. */
    readonly "api_endpoint_key": Omit<typeof tablesSchema.schemaType.tables["apiEndpointKey"], "accessorName"> & { readonly accessorName: "api_endpoint_key" };
    /** @deprecated Use `apiFieldMapping` instead. This alias will be removed in the next major version. */
    readonly "api_field_mapping": Omit<typeof tablesSchema.schemaType.tables["apiFieldMapping"], "accessorName"> & { readonly accessorName: "api_field_mapping" };
    /** @deprecated Use `blockAccessRule` instead. This alias will be removed in the next major version. */
    readonly "block_access_rule": Omit<typeof tablesSchema.schemaType.tables["blockAccessRule"], "accessorName"> & { readonly accessorName: "block_access_rule" };
    /** @deprecated Use `componentNode` instead. This alias will be removed in the next major version. */
    readonly "component_node": Omit<typeof tablesSchema.schemaType.tables["componentNode"], "accessorName"> & { readonly accessorName: "component_node" };
    /** @deprecated Use `componentTypeDefinition` instead. This alias will be removed in the next major version. */
    readonly "component_type_definition": Omit<typeof tablesSchema.schemaType.tables["componentTypeDefinition"], "accessorName"> & { readonly accessorName: "component_type_definition" };
    /** @deprecated Use `componentYjsState` instead. This alias will be removed in the next major version. */
    readonly "component_yjs_state": Omit<typeof tablesSchema.schemaType.tables["componentYjsState"], "accessorName"> & { readonly accessorName: "component_yjs_state" };
    /** @deprecated Use `databaseRowMarker` instead. This alias will be removed in the next major version. */
    readonly "database_row_marker": Omit<typeof tablesSchema.schemaType.tables["databaseRowMarker"], "accessorName"> & { readonly accessorName: "database_row_marker" };
    /** @deprecated Use `databaseSchema` instead. This alias will be removed in the next major version. */
    readonly "database_schema": Omit<typeof tablesSchema.schemaType.tables["databaseSchema"], "accessorName"> & { readonly accessorName: "database_schema" };
    /** @deprecated Use `databaseView` instead. This alias will be removed in the next major version. */
    readonly "database_view": Omit<typeof tablesSchema.schemaType.tables["databaseView"], "accessorName"> & { readonly accessorName: "database_view" };
    /** @deprecated Use `idCounter` instead. This alias will be removed in the next major version. */
    readonly "id_counter": Omit<typeof tablesSchema.schemaType.tables["idCounter"], "accessorName"> & { readonly accessorName: "id_counter" };
    /** @deprecated Use `loginResult` instead. This alias will be removed in the next major version. */
    readonly "login_result": Omit<typeof tablesSchema.schemaType.tables["loginResult"], "accessorName"> & { readonly accessorName: "login_result" };
    /** @deprecated Use `migrationState` instead. This alias will be removed in the next major version. */
    readonly "migration_state": Omit<typeof tablesSchema.schemaType.tables["migrationState"], "accessorName"> & { readonly accessorName: "migration_state" };
    /** @deprecated Use `moduleInstallMeta` instead. This alias will be removed in the next major version. */
    readonly "module_install_meta": Omit<typeof tablesSchema.schemaType.tables["moduleInstallMeta"], "accessorName"> & { readonly accessorName: "module_install_meta" };
    /** @deprecated Use `pageAccessRequest` instead. This alias will be removed in the next major version. */
    readonly "page_access_request": Omit<typeof tablesSchema.schemaType.tables["pageAccessRequest"], "accessorName"> & { readonly accessorName: "page_access_request" };
    /** @deprecated Use `pageAccessRule` instead. This alias will be removed in the next major version. */
    readonly "page_access_rule": Omit<typeof tablesSchema.schemaType.tables["pageAccessRule"], "accessorName"> & { readonly accessorName: "page_access_rule" };
    /** @deprecated Use `pageContent` instead. This alias will be removed in the next major version. */
    readonly "page_content": Omit<typeof tablesSchema.schemaType.tables["pageContent"], "accessorName"> & { readonly accessorName: "page_content" };
    /** @deprecated Use `pagePropertyValue` instead. This alias will be removed in the next major version. */
    readonly "page_property_value": Omit<typeof tablesSchema.schemaType.tables["pagePropertyValue"], "accessorName"> & { readonly accessorName: "page_property_value" };
    /** @deprecated Use `pagePropertyValueHistory` instead. This alias will be removed in the next major version. */
    readonly "page_property_value_history": Omit<typeof tablesSchema.schemaType.tables["pagePropertyValueHistory"], "accessorName"> & { readonly accessorName: "page_property_value_history" };
    /** @deprecated Use `pageSnapshot` instead. This alias will be removed in the next major version. */
    readonly "page_snapshot": Omit<typeof tablesSchema.schemaType.tables["pageSnapshot"], "accessorName"> & { readonly accessorName: "page_snapshot" };
    /** @deprecated Use `pageYjsState` instead. This alias will be removed in the next major version. */
    readonly "page_yjs_state": Omit<typeof tablesSchema.schemaType.tables["pageYjsState"], "accessorName"> & { readonly accessorName: "page_yjs_state" };
    /** @deprecated Use `propertyDefinition` instead. This alias will be removed in the next major version. */
    readonly "property_definition": Omit<typeof tablesSchema.schemaType.tables["propertyDefinition"], "accessorName"> & { readonly accessorName: "property_definition" };
    /** @deprecated Use `userPreference` instead. This alias will be removed in the next major version. */
    readonly "user_preference": Omit<typeof tablesSchema.schemaType.tables["userPreference"], "accessorName"> & { readonly accessorName: "user_preference" };
    /** @deprecated Use `workspaceSetting` instead. This alias will be removed in the next major version. */
    readonly "workspace_setting": Omit<typeof tablesSchema.schemaType.tables["workspaceSetting"], "accessorName"> & { readonly accessorName: "workspace_setting" };
    /** @deprecated Use `apiEndpointKeyLookup` instead. This alias will be removed in the next major version. */
    readonly "api_endpoint_key_lookup": Omit<typeof tablesSchema.schemaType.tables["apiEndpointKeyLookup"], "accessorName"> & { readonly accessorName: "api_endpoint_key_lookup" };
    /** @deprecated Use `readableComponents` instead. This alias will be removed in the next major version. */
    readonly "readable_components": Omit<typeof tablesSchema.schemaType.tables["readableComponents"], "accessorName"> & { readonly accessorName: "readable_components" };
    /** @deprecated Use `readablePages` instead. This alias will be removed in the next major version. */
    readonly "readable_pages": Omit<typeof tablesSchema.schemaType.tables["readablePages"], "accessorName"> & { readonly accessorName: "readable_pages" };
    /** @deprecated Use `readableReviewSnapshots` instead. This alias will be removed in the next major version. */
    readonly "readable_review_snapshots": Omit<typeof tablesSchema.schemaType.tables["readableReviewSnapshots"], "accessorName"> & { readonly accessorName: "readable_review_snapshots" };
    /** @deprecated Use `readableSchemas` instead. This alias will be removed in the next major version. */
    readonly "readable_schemas": Omit<typeof tablesSchema.schemaType.tables["readableSchemas"], "accessorName"> & { readonly accessorName: "readable_schemas" };
  };
};

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.10.1" as const,
  },
  tables: tablesSchema.schemaType.tables as __SchemaWithTableAccessorAliases["tables"],
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  __SchemaWithTableAccessorAliases,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

const tableAccessorAliases = {
  "api_call_log": "apiCallLog",
  "api_endpoint": "apiEndpoint",
  "api_endpoint_key": "apiEndpointKey",
  "api_field_mapping": "apiFieldMapping",
  "block_access_rule": "blockAccessRule",
  "component_node": "componentNode",
  "component_type_definition": "componentTypeDefinition",
  "component_yjs_state": "componentYjsState",
  "database_row_marker": "databaseRowMarker",
  "database_schema": "databaseSchema",
  "database_view": "databaseView",
  "id_counter": "idCounter",
  "login_result": "loginResult",
  "migration_state": "migrationState",
  "module_install_meta": "moduleInstallMeta",
  "page_access_request": "pageAccessRequest",
  "page_access_rule": "pageAccessRule",
  "page_content": "pageContent",
  "page_property_value": "pagePropertyValue",
  "page_property_value_history": "pagePropertyValueHistory",
  "page_snapshot": "pageSnapshot",
  "page_yjs_state": "pageYjsState",
  "property_definition": "propertyDefinition",
  "user_preference": "userPreference",
  "workspace_setting": "workspaceSetting",
  "api_endpoint_key_lookup": "apiEndpointKeyLookup",
  "readable_components": "readableComponents",
  "readable_pages": "readablePages",
  "readable_review_snapshots": "readableReviewSnapshots",
  "readable_schemas": "readableSchemas",
} as const;

function __withTableAccessorAliases<T extends object>(target: T, freeze = false): T {
  const out = Object.create(Object.getPrototypeOf(target)) as T & Record<string, unknown>;
  Object.defineProperties(out, Object.getOwnPropertyDescriptors(target));
  for (const [deprecatedAccessor, targetAccessor] of Object.entries(tableAccessorAliases)) {
    if (deprecatedAccessor in out) {
      continue;
    }
    Object.defineProperty(out, deprecatedAccessor, {
      enumerable: true,
      configurable: false,
      get: () => out[targetAccessor],
    });
  }
  return freeze ? Object.freeze(out) : out;
}

type __DbViewBase = __DbConnectionImpl<typeof REMOTE_MODULE>["db"];
export type DbView = __DbViewBase & {
  /** @deprecated Use `apiCallLog` instead. This alias will be removed in the next major version. */
  readonly "api_call_log": __DbViewBase["apiCallLog"];
  /** @deprecated Use `apiEndpoint` instead. This alias will be removed in the next major version. */
  readonly "api_endpoint": __DbViewBase["apiEndpoint"];
  /** @deprecated Use `apiEndpointKey` instead. This alias will be removed in the next major version. */
  readonly "api_endpoint_key": __DbViewBase["apiEndpointKey"];
  /** @deprecated Use `apiFieldMapping` instead. This alias will be removed in the next major version. */
  readonly "api_field_mapping": __DbViewBase["apiFieldMapping"];
  /** @deprecated Use `blockAccessRule` instead. This alias will be removed in the next major version. */
  readonly "block_access_rule": __DbViewBase["blockAccessRule"];
  /** @deprecated Use `componentNode` instead. This alias will be removed in the next major version. */
  readonly "component_node": __DbViewBase["componentNode"];
  /** @deprecated Use `componentTypeDefinition` instead. This alias will be removed in the next major version. */
  readonly "component_type_definition": __DbViewBase["componentTypeDefinition"];
  /** @deprecated Use `componentYjsState` instead. This alias will be removed in the next major version. */
  readonly "component_yjs_state": __DbViewBase["componentYjsState"];
  /** @deprecated Use `databaseRowMarker` instead. This alias will be removed in the next major version. */
  readonly "database_row_marker": __DbViewBase["databaseRowMarker"];
  /** @deprecated Use `databaseSchema` instead. This alias will be removed in the next major version. */
  readonly "database_schema": __DbViewBase["databaseSchema"];
  /** @deprecated Use `databaseView` instead. This alias will be removed in the next major version. */
  readonly "database_view": __DbViewBase["databaseView"];
  /** @deprecated Use `idCounter` instead. This alias will be removed in the next major version. */
  readonly "id_counter": __DbViewBase["idCounter"];
  /** @deprecated Use `loginResult` instead. This alias will be removed in the next major version. */
  readonly "login_result": __DbViewBase["loginResult"];
  /** @deprecated Use `migrationState` instead. This alias will be removed in the next major version. */
  readonly "migration_state": __DbViewBase["migrationState"];
  /** @deprecated Use `moduleInstallMeta` instead. This alias will be removed in the next major version. */
  readonly "module_install_meta": __DbViewBase["moduleInstallMeta"];
  /** @deprecated Use `pageAccessRequest` instead. This alias will be removed in the next major version. */
  readonly "page_access_request": __DbViewBase["pageAccessRequest"];
  /** @deprecated Use `pageAccessRule` instead. This alias will be removed in the next major version. */
  readonly "page_access_rule": __DbViewBase["pageAccessRule"];
  /** @deprecated Use `pageContent` instead. This alias will be removed in the next major version. */
  readonly "page_content": __DbViewBase["pageContent"];
  /** @deprecated Use `pagePropertyValue` instead. This alias will be removed in the next major version. */
  readonly "page_property_value": __DbViewBase["pagePropertyValue"];
  /** @deprecated Use `pagePropertyValueHistory` instead. This alias will be removed in the next major version. */
  readonly "page_property_value_history": __DbViewBase["pagePropertyValueHistory"];
  /** @deprecated Use `pageSnapshot` instead. This alias will be removed in the next major version. */
  readonly "page_snapshot": __DbViewBase["pageSnapshot"];
  /** @deprecated Use `pageYjsState` instead. This alias will be removed in the next major version. */
  readonly "page_yjs_state": __DbViewBase["pageYjsState"];
  /** @deprecated Use `propertyDefinition` instead. This alias will be removed in the next major version. */
  readonly "property_definition": __DbViewBase["propertyDefinition"];
  /** @deprecated Use `userPreference` instead. This alias will be removed in the next major version. */
  readonly "user_preference": __DbViewBase["userPreference"];
  /** @deprecated Use `workspaceSetting` instead. This alias will be removed in the next major version. */
  readonly "workspace_setting": __DbViewBase["workspaceSetting"];
  /** @deprecated Use `apiEndpointKeyLookup` instead. This alias will be removed in the next major version. */
  readonly "api_endpoint_key_lookup": __DbViewBase["apiEndpointKeyLookup"];
  /** @deprecated Use `readableComponents` instead. This alias will be removed in the next major version. */
  readonly "readable_components": __DbViewBase["readableComponents"];
  /** @deprecated Use `readablePages` instead. This alias will be removed in the next major version. */
  readonly "readable_pages": __DbViewBase["readablePages"];
  /** @deprecated Use `readableReviewSnapshots` instead. This alias will be removed in the next major version. */
  readonly "readable_review_snapshots": __DbViewBase["readableReviewSnapshots"];
  /** @deprecated Use `readableSchemas` instead. This alias will be removed in the next major version. */
  readonly "readable_schemas": __DbViewBase["readableSchemas"];
};

type __TablesBase = __QueryBuilder<typeof tablesSchema.schemaType>;
export type Tables = __TablesBase & {
  /** @deprecated Use `apiCallLog` instead. This alias will be removed in the next major version. */
  readonly "api_call_log": __TablesBase["apiCallLog"];
  /** @deprecated Use `apiEndpoint` instead. This alias will be removed in the next major version. */
  readonly "api_endpoint": __TablesBase["apiEndpoint"];
  /** @deprecated Use `apiEndpointKey` instead. This alias will be removed in the next major version. */
  readonly "api_endpoint_key": __TablesBase["apiEndpointKey"];
  /** @deprecated Use `apiFieldMapping` instead. This alias will be removed in the next major version. */
  readonly "api_field_mapping": __TablesBase["apiFieldMapping"];
  /** @deprecated Use `blockAccessRule` instead. This alias will be removed in the next major version. */
  readonly "block_access_rule": __TablesBase["blockAccessRule"];
  /** @deprecated Use `componentNode` instead. This alias will be removed in the next major version. */
  readonly "component_node": __TablesBase["componentNode"];
  /** @deprecated Use `componentTypeDefinition` instead. This alias will be removed in the next major version. */
  readonly "component_type_definition": __TablesBase["componentTypeDefinition"];
  /** @deprecated Use `componentYjsState` instead. This alias will be removed in the next major version. */
  readonly "component_yjs_state": __TablesBase["componentYjsState"];
  /** @deprecated Use `databaseRowMarker` instead. This alias will be removed in the next major version. */
  readonly "database_row_marker": __TablesBase["databaseRowMarker"];
  /** @deprecated Use `databaseSchema` instead. This alias will be removed in the next major version. */
  readonly "database_schema": __TablesBase["databaseSchema"];
  /** @deprecated Use `databaseView` instead. This alias will be removed in the next major version. */
  readonly "database_view": __TablesBase["databaseView"];
  /** @deprecated Use `idCounter` instead. This alias will be removed in the next major version. */
  readonly "id_counter": __TablesBase["idCounter"];
  /** @deprecated Use `loginResult` instead. This alias will be removed in the next major version. */
  readonly "login_result": __TablesBase["loginResult"];
  /** @deprecated Use `migrationState` instead. This alias will be removed in the next major version. */
  readonly "migration_state": __TablesBase["migrationState"];
  /** @deprecated Use `moduleInstallMeta` instead. This alias will be removed in the next major version. */
  readonly "module_install_meta": __TablesBase["moduleInstallMeta"];
  /** @deprecated Use `pageAccessRequest` instead. This alias will be removed in the next major version. */
  readonly "page_access_request": __TablesBase["pageAccessRequest"];
  /** @deprecated Use `pageAccessRule` instead. This alias will be removed in the next major version. */
  readonly "page_access_rule": __TablesBase["pageAccessRule"];
  /** @deprecated Use `pageContent` instead. This alias will be removed in the next major version. */
  readonly "page_content": __TablesBase["pageContent"];
  /** @deprecated Use `pagePropertyValue` instead. This alias will be removed in the next major version. */
  readonly "page_property_value": __TablesBase["pagePropertyValue"];
  /** @deprecated Use `pagePropertyValueHistory` instead. This alias will be removed in the next major version. */
  readonly "page_property_value_history": __TablesBase["pagePropertyValueHistory"];
  /** @deprecated Use `pageSnapshot` instead. This alias will be removed in the next major version. */
  readonly "page_snapshot": __TablesBase["pageSnapshot"];
  /** @deprecated Use `pageYjsState` instead. This alias will be removed in the next major version. */
  readonly "page_yjs_state": __TablesBase["pageYjsState"];
  /** @deprecated Use `propertyDefinition` instead. This alias will be removed in the next major version. */
  readonly "property_definition": __TablesBase["propertyDefinition"];
  /** @deprecated Use `userPreference` instead. This alias will be removed in the next major version. */
  readonly "user_preference": __TablesBase["userPreference"];
  /** @deprecated Use `workspaceSetting` instead. This alias will be removed in the next major version. */
  readonly "workspace_setting": __TablesBase["workspaceSetting"];
  /** @deprecated Use `apiEndpointKeyLookup` instead. This alias will be removed in the next major version. */
  readonly "api_endpoint_key_lookup": __TablesBase["apiEndpointKeyLookup"];
  /** @deprecated Use `readableComponents` instead. This alias will be removed in the next major version. */
  readonly "readable_components": __TablesBase["readableComponents"];
  /** @deprecated Use `readablePages` instead. This alias will be removed in the next major version. */
  readonly "readable_pages": __TablesBase["readablePages"];
  /** @deprecated Use `readableReviewSnapshots` instead. This alias will be removed in the next major version. */
  readonly "readable_review_snapshots": __TablesBase["readableReviewSnapshots"];
  /** @deprecated Use `readableSchemas` instead. This alias will be removed in the next major version. */
  readonly "readable_schemas": __TablesBase["readableSchemas"];
};

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
const tablesBase: __TablesBase = __makeQueryBuilder(tablesSchema.schemaType);
export const tables: Tables = __withTableAccessorAliases(tablesBase, true) as Tables;

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = Omit<__EventContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = Omit<__ReducerEventContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = Omit<__SubscriptionEventContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The context type returned in callbacks for error events. */
export type ErrorContext = Omit<__ErrorContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  declare db: DbView;

  constructor(config: __DbConnectionConfig<typeof REMOTE_MODULE>) {
    super(config);
    this.db = __withTableAccessorAliases(this.db) as DbView;
  }

  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

