// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  Principal,
  Permission,
  AccessRequestStatus,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  pageId: __t.u64().name("page_id"),
  get principal() {
    return Principal;
  },
  get permission() {
    return Permission;
  },
  requestedBy: __t.identity().name("requested_by"),
  reason: __t.string(),
  get status() {
    return AccessRequestStatus;
  },
  requestedAt: __t.timestamp().name("requested_at"),
  resolvedBy: __t.option(__t.identity()).name("resolved_by"),
  resolvedAt: __t.option(__t.timestamp()).name("resolved_at"),
});
