// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  ActorType,
  PageType,
  PageContentFormat,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  parentId: __t.option(__t.u64()).name("parent_id"),
  get pageType() {
    return PageType.name("page_type");
  },
  title: __t.string(),
  sortOrder: __t.u32().name("sort_order"),
  get createdBy() {
    return ActorType.name("created_by");
  },
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
  deletedAt: __t.option(__t.timestamp()).name("deleted_at"),
  icon: __t.option(__t.string()),
  parentPk: __t.u64().name("parent_pk"),
  isHidden: __t.bool().name("is_hidden"),
  get contentFormat() {
    return PageContentFormat.name("content_format");
  },
});
