// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

// The tagged union or sum type for the algebraic type `AccessRequestStatus`.
export const AccessRequestStatus = __t.enum("AccessRequestStatus", {
  Pending: __t.unit(),
  Approved: __t.unit(),
  Denied: __t.unit(),
});
export type AccessRequestStatus = __Infer<typeof AccessRequestStatus>;

// The tagged union or sum type for the algebraic type `ActorType`.
export const ActorType = __t.enum("ActorType", {
  Human: __t.unit(),
  Agent: __t.string(),
});
export type ActorType = __Infer<typeof ActorType>;

export const AiPropertyValue = __t.object("AiPropertyValue", {
  output: __t.string(),
  evaluationId: __t.u64(),
  isStale: __t.bool(),
});
export type AiPropertyValue = __Infer<typeof AiPropertyValue>;

export const ApiCallLog = __t.object("ApiCallLog", {
  id: __t.u64(),
  endpointId: __t.u64(),
  keyId: __t.option(__t.u64()),
  get method() {
    return HttpMethod;
  },
  path: __t.string(),
  statusCode: __t.u16(),
  latencyMs: __t.u32(),
  callerIp: __t.option(__t.string()),
  errorMessage: __t.option(__t.string()),
  at: __t.timestamp(),
});
export type ApiCallLog = __Infer<typeof ApiCallLog>;

export const ApiEndpoint = __t.object("ApiEndpoint", {
  id: __t.u64(),
  databasePageId: __t.u64(),
  slug: __t.string(),
  displayName: __t.string(),
  description: __t.string(),
  get allowedMethods() {
    return __t.array(HttpMethod);
  },
  requireAuth: __t.bool(),
  createdBy: __t.identity(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type ApiEndpoint = __Infer<typeof ApiEndpoint>;

export const ApiEndpointKey = __t.object("ApiEndpointKey", {
  id: __t.u64(),
  endpointId: __t.u64(),
  keyHash: __t.string(),
  label: __t.string(),
  get allowedMethods() {
    return __t.array(HttpMethod);
  },
  createdBy: __t.identity(),
  createdAt: __t.timestamp(),
  lastUsedAt: __t.option(__t.timestamp()),
  expiresAt: __t.option(__t.timestamp()),
});
export type ApiEndpointKey = __Infer<typeof ApiEndpointKey>;

export const ApiEndpointKeyLookupRow = __t.object("ApiEndpointKeyLookupRow", {
  id: __t.u64(),
  endpointId: __t.u64(),
  keyHash: __t.string(),
  get allowedMethods() {
    return __t.array(HttpMethod);
  },
  expiresAt: __t.option(__t.timestamp()),
});
export type ApiEndpointKeyLookupRow = __Infer<typeof ApiEndpointKeyLookupRow>;

export const ApiFieldMapping = __t.object("ApiFieldMapping", {
  id: __t.u64(),
  endpointId: __t.u64(),
  propertyDefinitionId: __t.u64(),
  fieldName: __t.string(),
  requiredOnCreate: __t.bool(),
  defaultValue: __t.option(__t.string()),
  readOnly: __t.bool(),
  fieldOrder: __t.u32(),
});
export type ApiFieldMapping = __Infer<typeof ApiFieldMapping>;

export const Attachment = __t.object("Attachment", {
  id: __t.u64(),
  pageId: __t.u64(),
  filename: __t.string(),
  contentType: __t.string(),
  storageKey: __t.string(),
  sizeBytes: __t.u64(),
  createdAt: __t.timestamp(),
});
export type Attachment = __Infer<typeof Attachment>;

export const BlockAccessRule = __t.object("BlockAccessRule", {
  id: __t.u64(),
  pageId: __t.u64(),
  blockId: __t.string(),
  get principal() {
    return Principal;
  },
  get permission() {
    return Permission;
  },
  grantedBy: __t.identity(),
  grantedAt: __t.timestamp(),
});
export type BlockAccessRule = __Infer<typeof BlockAccessRule>;

export const BlockContentUpdateInput = __t.object("BlockContentUpdateInput", {
  componentId: __t.u64(),
  data: __t.byteArray(),
});
export type BlockContentUpdateInput = __Infer<typeof BlockContentUpdateInput>;

// The tagged union or sum type for the algebraic type `ComponentCapability`.
export const ComponentCapability = __t.enum("ComponentCapability", {
  ReadsDatabase: __t.unit(),
  ReadsProperty: __t.unit(),
  WritesDatabase: __t.unit(),
  WritesProperty: __t.unit(),
  DeletesRow: __t.unit(),
  NavigatesToPage: __t.unit(),
  OpensExternalUrl: __t.unit(),
  TriggersAutomation: __t.unit(),
});
export type ComponentCapability = __Infer<typeof ComponentCapability>;

export const ComponentNode = __t.object("ComponentNode", {
  id: __t.u64(),
  surfaceId: __t.u64(),
  parentId: __t.option(__t.u64()),
  componentType: __t.string(),
  props: __t.string(),
  order: __t.u32(),
  get createdBy() {
    return ActorType;
  },
  get updatedBy() {
    return ActorType;
  },
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
  deletedAt: __t.option(__t.timestamp()),
});
export type ComponentNode = __Infer<typeof ComponentNode>;

export const ComponentTypeDefinition = __t.object("ComponentTypeDefinition", {
  id: __t.u64(),
  componentType: __t.string(),
  displayName: __t.string(),
  description: __t.string(),
  propSchema: __t.string(),
  get capabilities() {
    return __t.array(ComponentCapability);
  },
  hasYjsState: __t.bool(),
  acceptsChildren: __t.bool(),
  isBuiltin: __t.bool(),
  registeredBy: __t.identity(),
  createdAt: __t.timestamp(),
});
export type ComponentTypeDefinition = __Infer<typeof ComponentTypeDefinition>;

export const ComponentYjsState = __t.object("ComponentYjsState", {
  componentNodeId: __t.u64(),
  data: __t.byteArray(),
  updatedAt: __t.timestamp(),
});
export type ComponentYjsState = __Infer<typeof ComponentYjsState>;

export const DatabaseRowMarker = __t.object("DatabaseRowMarker", {
  id: __t.u64(),
  clientRequestId: __t.string(),
  pageId: __t.u64(),
  createdAt: __t.timestamp(),
});
export type DatabaseRowMarker = __Infer<typeof DatabaseRowMarker>;

export const DatabaseSchema = __t.object("DatabaseSchema", {
  id: __t.u64(),
  pageId: __t.u64(),
  name: __t.string(),
  config: __t.option(__t.string()),
  parentSchemaId: __t.option(__t.u64()),
});
export type DatabaseSchema = __Infer<typeof DatabaseSchema>;

export const DatabaseView = __t.object("DatabaseView", {
  id: __t.u64(),
  pageId: __t.u64(),
  name: __t.string(),
  get viewType() {
    return ViewType;
  },
  config: __t.string(),
  isDefault: __t.bool(),
  ownerIdentity: __t.option(__t.string()),
  get createdBy() {
    return ActorType;
  },
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type DatabaseView = __Infer<typeof DatabaseView>;

export const DocBlockInput = __t.object("DocBlockInput", {
  componentType: __t.string(),
  propsJson: __t.string(),
  yjsState: __t.option(__t.byteArray()),
});
export type DocBlockInput = __Infer<typeof DocBlockInput>;

export const FileRef = __t.object("FileRef", {
  name: __t.string(),
  objectId: __t.string(),
  externalUrl: __t.string(),
});
export type FileRef = __Infer<typeof FileRef>;

// The tagged union or sum type for the algebraic type `HttpMethod`.
export const HttpMethod = __t.enum("HttpMethod", {
  Get: __t.unit(),
  Post: __t.unit(),
  Patch: __t.unit(),
  Delete: __t.unit(),
});
export type HttpMethod = __Infer<typeof HttpMethod>;

export const IdCounter = __t.object("IdCounter", {
  name: __t.string(),
  value: __t.u64(),
});
export type IdCounter = __Infer<typeof IdCounter>;

export const ImportSession = __t.object("ImportSession", {
  id: __t.u64(),
  createdBy: __t.identity(),
  startedAt: __t.timestamp(),
  lastSeq: __t.u32(),
});
export type ImportSession = __Infer<typeof ImportSession>;

export const ImportSessionCount = __t.object("ImportSessionCount", {
  id: __t.u64(),
  tableName: __t.string(),
  applied: __t.u64(),
  skipped: __t.u64(),
});
export type ImportSessionCount = __Infer<typeof ImportSessionCount>;

export const LocalLoginAttempt = __t.object("LocalLoginAttempt", {
  email: __t.string(),
  windowStart: __t.i64(),
  attempts: __t.u32(),
});
export type LocalLoginAttempt = __Infer<typeof LocalLoginAttempt>;

export const LoginResult = __t.object("LoginResult", {
  identity: __t.identity(),
  success: __t.bool(),
  message: __t.string(),
  at: __t.timestamp(),
});
export type LoginResult = __Infer<typeof LoginResult>;

export const MigrationState = __t.object("MigrationState", {
  key: __t.string(),
  completedAt: __t.timestamp(),
  moduleVersion: __t.string(),
});
export type MigrationState = __Infer<typeof MigrationState>;

export const ModuleInstallMeta = __t.object("ModuleInstallMeta", {
  id: __t.u8(),
  publisherIdentity: __t.identity(),
});
export type ModuleInstallMeta = __Infer<typeof ModuleInstallMeta>;

export const OidcTrustPolicy = __t.object("OidcTrustPolicy", {
  id: __t.u8(),
  issuer: __t.string(),
  audience: __t.string(),
});
export type OidcTrustPolicy = __Infer<typeof OidcTrustPolicy>;

export const Page = __t.object("Page", {
  id: __t.u64(),
  parentId: __t.option(__t.u64()),
  get pageType() {
    return PageType;
  },
  title: __t.string(),
  sortOrder: __t.u32(),
  get createdBy() {
    return ActorType;
  },
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
  deletedAt: __t.option(__t.timestamp()),
  icon: __t.option(__t.string()),
  parentPk: __t.u64(),
  isHidden: __t.bool(),
  get contentFormat() {
    return PageContentFormat;
  },
});
export type Page = __Infer<typeof Page>;

export const PageAccessRequest = __t.object("PageAccessRequest", {
  id: __t.u64(),
  pageId: __t.u64(),
  get principal() {
    return Principal;
  },
  get permission() {
    return Permission;
  },
  requestedBy: __t.identity(),
  reason: __t.string(),
  get status() {
    return AccessRequestStatus;
  },
  requestedAt: __t.timestamp(),
  resolvedBy: __t.option(__t.identity()),
  resolvedAt: __t.option(__t.timestamp()),
});
export type PageAccessRequest = __Infer<typeof PageAccessRequest>;

export const PageAccessRule = __t.object("PageAccessRule", {
  id: __t.u64(),
  pageId: __t.u64(),
  get principal() {
    return Principal;
  },
  get permission() {
    return Permission;
  },
  grantedBy: __t.identity(),
  grantedAt: __t.timestamp(),
});
export type PageAccessRule = __Infer<typeof PageAccessRule>;

export const PageContent = __t.object("PageContent", {
  pageId: __t.u64(),
  content: __t.string(),
  updatedAt: __t.timestamp(),
});
export type PageContent = __Infer<typeof PageContent>;

// The tagged union or sum type for the algebraic type `PageContentFormat`.
export const PageContentFormat = __t.enum("PageContentFormat", {
  BlockNote: __t.unit(),
  ComponentTree: __t.unit(),
});
export type PageContentFormat = __Infer<typeof PageContentFormat>;

export const PagePropertyValue = __t.object("PagePropertyValue", {
  id: __t.u64(),
  pageId: __t.u64(),
  propertyDefinitionId: __t.u64(),
  get value() {
    return PropertyValue;
  },
});
export type PagePropertyValue = __Infer<typeof PagePropertyValue>;

export const PagePropertyValueHistory = __t.object("PagePropertyValueHistory", {
  id: __t.u64(),
  pageId: __t.u64(),
  propertyDefinitionId: __t.u64(),
  get value() {
    return PropertyValue;
  },
  isCurrent: __t.bool(),
  changedAt: __t.timestamp(),
  get changedBy() {
    return ActorType;
  },
});
export type PagePropertyValueHistory = __Infer<typeof PagePropertyValueHistory>;

export const PageSnapshot = __t.object("PageSnapshot", {
  id: __t.u64(),
  pageId: __t.u64(),
  title: __t.string(),
  content: __t.string(),
  snapshotAt: __t.timestamp(),
  get createdBy() {
    return ActorType;
  },
  get snapshotType() {
    return SnapshotType;
  },
});
export type PageSnapshot = __Infer<typeof PageSnapshot>;

// The tagged union or sum type for the algebraic type `PageType`.
export const PageType = __t.enum("PageType", {
  Doc: __t.unit(),
  Database: __t.unit(),
});
export type PageType = __Infer<typeof PageType>;

export const PageYjsState = __t.object("PageYjsState", {
  pageId: __t.u64(),
  data: __t.byteArray(),
  updatedAt: __t.timestamp(),
});
export type PageYjsState = __Infer<typeof PageYjsState>;

// The tagged union or sum type for the algebraic type `Permission`.
export const Permission = __t.enum("Permission", {
  Read: __t.unit(),
  Write: __t.unit(),
});
export type Permission = __Infer<typeof Permission>;

// The tagged union or sum type for the algebraic type `Principal`.
export const Principal = __t.enum("Principal", {
  WorkspaceMember: __t.identity(),
});
export type Principal = __Infer<typeof Principal>;

export const PropertyDefinition = __t.object("PropertyDefinition", {
  id: __t.u64(),
  schemaId: __t.u64(),
  name: __t.string(),
  get propertyType() {
    return PropertyType;
  },
  config: __t.string(),
  order: __t.u32(),
});
export type PropertyDefinition = __Infer<typeof PropertyDefinition>;

// The tagged union or sum type for the algebraic type `PropertyType`.
export const PropertyType = __t.enum("PropertyType", {
  Text: __t.unit(),
  Number: __t.unit(),
  Date: __t.unit(),
  Select: __t.unit(),
  MultiSelect: __t.unit(),
  Relation: __t.unit(),
  Checkbox: __t.unit(),
  Url: __t.unit(),
  Person: __t.unit(),
  Ai: __t.unit(),
  Formula: __t.unit(),
  Rollup: __t.unit(),
  File: __t.unit(),
});
export type PropertyType = __Infer<typeof PropertyType>;

// The tagged union or sum type for the algebraic type `PropertyValue`.
export const PropertyValue = __t.enum("PropertyValue", {
  Text: __t.string(),
  Number: __t.f64(),
  Date: __t.u64(),
  Select: __t.string(),
  MultiSelect: __t.array(__t.string()),
  Relation: __t.array(__t.u64()),
  Checkbox: __t.bool(),
  Url: __t.string(),
  Person: __t.array(__t.string()),
  get Ai() {
    return AiPropertyValue;
  },
  get File() {
    return __t.array(FileRef);
  },
});
export type PropertyValue = __Infer<typeof PropertyValue>;

export const PropertyValueInput = __t.object("PropertyValueInput", {
  propertyDefinitionId: __t.u64(),
  get value() {
    return PropertyValue;
  },
});
export type PropertyValueInput = __Infer<typeof PropertyValueInput>;

export const ReadableResource = __t.object("ReadableResource", {
  id: __t.u64(),
});
export type ReadableResource = __Infer<typeof ReadableResource>;

// The tagged union or sum type for the algebraic type `SnapshotType`.
export const SnapshotType = __t.enum("SnapshotType", {
  Manual: __t.unit(),
  Periodic: __t.unit(),
  PreAgentEdit: __t.unit(),
  PostAgentEdit: __t.unit(),
});
export type SnapshotType = __Infer<typeof SnapshotType>;

export const TrashPurgeTick = __t.object("TrashPurgeTick", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type TrashPurgeTick = __Infer<typeof TrashPurgeTick>;

export const User = __t.object("User", {
  identity: __t.identity(),
  name: __t.string(),
  email: __t.string(),
  isAuthenticated: __t.bool(),
  createdAt: __t.timestamp(),
  lastSeenAt: __t.timestamp(),
  isAdmin: __t.bool(),
});
export type User = __Infer<typeof User>;

export const UserCredential = __t.object("UserCredential", {
  email: __t.string(),
  name: __t.string(),
  passwordHash: __t.string(),
  createdAt: __t.timestamp(),
});
export type UserCredential = __Infer<typeof UserCredential>;

export const UserPreference = __t.object("UserPreference", {
  id: __t.u64(),
  identity: __t.identity(),
  key: __t.string(),
  valueJson: __t.string(),
  updatedAt: __t.timestamp(),
});
export type UserPreference = __Infer<typeof UserPreference>;

// The tagged union or sum type for the algebraic type `ViewType`.
export const ViewType = __t.enum("ViewType", {
  Grid: __t.unit(),
  List: __t.unit(),
  Kanban: __t.unit(),
  Calendar: __t.unit(),
  Gallery: __t.unit(),
});
export type ViewType = __Infer<typeof ViewType>;

export const WorkspaceSetting = __t.object("WorkspaceSetting", {
  id: __t.u64(),
  key: __t.string(),
  valueJson: __t.string(),
  updatedBy: __t.identity(),
  updatedAt: __t.timestamp(),
});
export type WorkspaceSetting = __Infer<typeof WorkspaceSetting>;

