// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  ComponentCapability,
} from "./types";

export default {
  typeId: __t.u64(),
  displayName: __t.option(__t.string()),
  description: __t.option(__t.string()),
  propSchemaJson: __t.option(__t.string()),
  get capabilities() {
    return __t.option(__t.array(ComponentCapability));
  },
};
